on:
  workflow_dispatch:
  schedule:
    # run every 4 hours
    - cron: '20 */4 * * *'
name: New Excavator
jobs:
  excavate:

    name: Excavate
    runs-on: windows-latest
    environment: Excavator
    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Checkout Bucket
        uses: actions/checkout@v4
        with:
          path: my_bucket
      - name: Checkout Scoop
        uses: actions/checkout@v4
        with:
          repository: ScoopInstaller/Scoop
          path: scoop_core
      - name: Excavate
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          curl -L `
            -H "Authorization: Bearer $env:GITHUB_TOKEN" `
            https://api.github.com/user
          curl -L `
            -H "Authorization: Bearer $env:GITHUB_TOKEN" `
            https://api.github.com/user/public_emails
          # $env:SCOOP_HOME="$(Convert-Path '.\scoop_core')"
          # cd .\my_bucket
          # .\bin\auto-pr.ps1 `
          #   -Push `
          #   -Upstream "${{ github.repository }}:${{ github.ref_name }}" `
          #   -OriginBranch "${{ github.ref_name }}"
